### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by zakaria-chahboun** [zakaria-chahboun/cute#5]
- [x] Println
- [x] Printlns
- [x] Printf
- [x] Check

### version: v1.1.0
- List (like *Printlns* but allows you to add lines dynamically)
     - [x] ~~Add(any)~~
     - [x] ~~Addf(string, ...any)~~
     - [x] Add(color, any)
     - [x] Addf(color, string, ...any)
     - [x] Print()

### version: v1.2.x
Support non-ASCII characters in the title box:
  - [x] Arabic *with tashkeel*
  - [x]  ABC languages: Greek, French, Spanish, German, Turkish, Indonesian ....
  - [x]  Russian - Ukrainian
  - [x] CJK: Chinese *(simplified / traditional)*
  - [x]  Japanese *(hiragana)* 
  - [x] Korean
  - [x] Hindi *(devanagari)*
  - [x] emojis
  - [x] release v1.2.x

### version: v1.x.x
support tables

**Comment by zakaria-chahboun** [comment]
## List
You can print a list of lines dynamically!

```go
list := cute.NewList("Yummy Juice!")
list.Add("4 strawberry")
list.Add("1 avocado")
list.Addf("%d ml %s", 500, "milk")
list.Print()
```

![06](https://user-images.githubusercontent.com/18173275/196071877-30ca3027-49ad-480d-bc0e-333272c465b5.png)

You can also specify the color message for each line:

```go
cute.SetTitleColor(cute.ColorBrightBlue)
list := cute.NewList("Yummy Juice!")

cute.SetMessageColor(cute.ColorBrightRed)
list.Add("4 strawberry")

cute.SetMessageColor(cute.ColorBrightGreen)
list.Add("1 avocado")

cute.SetMessageColor(cute.ColorWhite)
list.Addf("%d ml %s", 500, "milk")

list.Print()
```
![07](https://user-images.githubusercontent.com/18173275/196071921-c330f004-9082-4051-b927-b1edf4f4320b.png)

**Comment by zakaria-chahboun** [comment]
# List: Way 2


You can print a list of lines dynamically! You can also specify the color for each line:

```go
// juice recipe 🧃
list := cute.NewList(cute.ColorBrightBlue, "Yummy Juice!")
list.Add(cute.ColorBrightRed, "4 strawberry")
list.Add(cute.ColorBrightGreen, "1 avocado")
list.Addf(cute.ColorWhite, "%d ml %s", 500, "milk")
list.Print()
```
